### ISSUE TITLE
Operations: Website: Detailed Quarterly Impact Reports for 2023 not Displaying

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#101]
Broken links, click on the quarterly buttons:
[Impact Report](https://www.themade.org/impact-report/2023)

**Comment by PranavJayachand** [comment]
Weirdly enough, the direct link to this website doesn't load unless I navigate to it from the homepage.

**Comment by wynnmade** [comment]
Cmpleted.
