### ISSUE TITLE
Operations: Github: Update MADE-Initiatives Readme with Proposal Form

### ISSUE THREAD

**Issue by asajbel** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#108]
Proposal form: https://forms.gle/vfrudKJ8Pdiro8a19

The above proposal form should be put on the Readme for the MADE_Initiatives project in the proposal section. A rewrite of the section might also be necessary as it asks for 3D renders and other time intensive work just to get started.

**Comment by wynnmade** [comment]
Added to site and to the initiatives repo.
