### ISSUE TITLE
Operations: Website: Make proposal form scrollable

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#117]

**Comment by colemandsmith** [comment]
@wynnmade to clarify the requirement for the [proposal page](https://www.themade.org/proposals) - do we want to shrink the iframe the google form is in and make the form scrollable within the iframe?

**Comment by wynnmade** [comment]
Ah crud, sorry for the late response! Basically, it just needs to be compatible for all devices, phone + laptop.

**Comment by wynnmade** [comment]
Merged!
