### ISSUE TITLE
Museum: Restoration: iMac Repair

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#134]

**Comment by wynnmade** [comment]
- mason reported it wasn't turning on
- can confirm: it wasn't turning on. repeated presses of the power button and nothing
- i took it about halfway apart, and now it magically works again!
- it's back on the floor
- my best guess is that the plastic power button on the front panel wasn't properly aligning with the button on the front panel board. if/when this happens again, that's the biggest thing i'd look at — try to get something super slim in between the power button and surrounding bezel to try to goose its position and see if that improves.
- second guess is that i somehow magically fixed it when i pressed the CUDA reset button on the logic board (the CUDA is the power management chip)
- the two screws that were securing the logic board/drive cage were super stripped — i found it easiest to help them along with pliers. so to preserve the next restoration effort's sanity, i left them out/taped to the bottom of the cage.
- also note for the next restoration effort/the reason i don't exactly know what i did to fix it: there are three cables that connect the cage to the rest of the machine: video, power, and front panel. turns out if you connect power but not front panel and try to turn it on, it won't work because the power button isn't actually connected to the board. :expressionless: be smarter than i was and connect both cables when you're troubleshooting!

**Comment by wynnmade** [comment]
@cow-poke: yeah i don't love the idea that we're taking it apart every few months: the front panel is connected to/part of that whole clear translucent piece on the bottom there. at least 11 screws to get apart, and although i didn't break the plastic tabs on the front, i was pretty nervous about doing so.

**Comment by qst0** [comment]
Completed
this issue happened last year, we are still not 100% sure what is fixing it
