### ISSUE TITLE
Museum: SGI O2 Restoration/OpenGL demonstration

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#15]
We want to show the next generation of digital creators what the first version of OpenGL (eventually the de-facto common abstraction for shader development)! It was first developed by Silicon Graphics for their SGI machines, and we're restoring one for demonstration purposes. Come help us bring it up and determine best practices for maintenance!

**Comment by wynnmade** [comment]
Looking into setting up two VMs to more quickly iterate on boot process for the SGI.
https://github.com/unxmaal/booterizer

**Comment by wynnmade** [comment]
![Uploading sgi_o2.jpeg…]()

**Comment by andrewwatterson** [comment]
Maybe not a helpful suggestion, but using `booterizer` seems a bit overcomplicated here (unless we're putting the O2 on active display and expect to need to reimage it often). The O2 has an optical drive, and we can find IRIX install media.

So I will defer to the folks who have already thought about this, but if our main goal is to get the O2 booting into IRIX, we should be able to get that going in almost no time.

**Comment by andrewwatterson** [comment]
Separately, if we are going to put this on display/do any photo or video shoots, with some advance notice I'm happy to long-term-lend us the matching SGI flat panel display, [the 1600SW](https://en.wikipedia.org/wiki/SGI_1600SW). Note that we'll need to make sure our O2 has the 1600SW interface card: see the [pic here](https://computers.popcorn.cx/sgi/o2/o2-10.jpg) — the port labelled "Flat Panel Monitor" is the unusual [OpenLDI](https://en.wikipedia.org/wiki/OpenLDI) port we're looking for.

**Comment by wynnmade** [comment]
@andrewwatterson if you could come up with that media, that would be amazing! I'm down to go with any approach that would get this up and running.

**Comment by andrewwatterson** [comment]
Easy to find on archive.org — https://archive.org/details/overlays-2

I think the "Foundation" discs are probably the base install (I'm pretty sure "Overlays" are SGI-speak for updates) — you may or may not need the Installation Tools disc. I've never done this before!

Also don't forget to let the O2 show itself off on its own terms: https://archive.org/details/sgi-o2-out-of-box-experience-2.2

Happy to do a jam session! I can bring in all the above on original media if burning them seems daunting — I've been meaning to brush up my SGI skillz. I've also got a bunch of rando CDs with various apps — SoftImage? Lightwave? I don't actually know what any of these things do. But the links above could be helpful if folks want to self-power this project/minimize coordination.
