### ISSUE TITLE
Community: External: Supernatural 10/26: Development: Map Magnification

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#198]

**Comment by patreeceeo** [comment]
Does this correspond to anything in the Figma (https://www.figma.com/design/p2CEWUPXEta9cM9GBBnInM/MADE-CalAcad-Scavenger-Hunt?node-id=0-1&node-type=canvas)?

Is this basically just overriding the default pinch-zoom gesture?
