### ISSUE TITLE
Education: Funding: 11/11 Inspire Grant: 2 - Narrative Draft Finalization

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#203]
https://docs.google.com/document/d/1Qq7kHXHQDs1sOJHM9kz5IsxF4lMuL5fmGwcdJXQo5MQ/edit?usp=share_link

**Comment by Stacey-themade** [comment]
@wynnmade I made updates in the doc entitled "rewrite_assist_narrativeDraft". Some comments are still there for your feedback. Thanks!
