### ISSUE TITLE
Museum: Exhibits: DDR Pad

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#225]

**Comment by content-deleted** [comment]
I'm interested in helping with this, I have a flash stick already set up with stepmania configured to DDR supernova with bindings for most pads, as well as arcade beatmaps for most games up to DDR A (I can also filter those down to songs licensed in home console versions contained in the MADE collection if needed)

**Comment by wynnmade** [comment]
Closing issue as this appears stale.
