### ISSUE TITLE
Museum: Determine when exhibits need to be rotated when non-functional

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#25]
Specification for process of moving/replacing with new items.

**Comment by jesse-made** [comment]
I think exhibits generally have backups identified, so if they are non-functional the backups should be used. however if an exhibit were non-functional, we should certainly plan to change it out.

**Comment by wynnmade** [comment]
Going to close this for now. This seems to be more a function of volunteer support vs. needing spec.
