### ISSUE TITLE
Community: MOU for space usage of the MADE

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#29]

**Comment by wynnmade** [comment]
Moving this to Anders, as I think it's more important that someone on the floor who knows the issues addresses these.

**Comment by asajbel** [comment]
Is this a good template? https://docs.google.com/document/d/1Dr04X2y5292U_kPTjmZh5rSApbX9X5bq/edit?usp=sharing&ouid=105987918969604399868&rtpof=true&sd=true

**Comment by asajbel** [comment]
I got it from the US Department of Justice https://cops.usdoj.gov/pdf/tribal_training/MOU_MOA/Templates_and_Reference_Documents/Fillable_Template_MOU.docx

**Comment by asajbel** [comment]
Needs to be closed. MOU Template is available in the Drive.
