### ISSUE TITLE
Museum: Fix Super Mario Cabinet

### ISSUE THREAD

**Issue by jesse-made** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#30]

**Comment by jesse-made** [comment]
This machine is filthy has a broken p2 controller and the buttons are screwed

**Comment by wynnmade** [comment]
Break down into individual tasks.

**Comment by wynnmade** [comment]
@asajbel said:
Opened the cabinet up and fixed the screen being covered.

Then the problem with the 2-Player button not working was investigated. The wire leading connecting the second player controls to the ground on the logic board was broken. It was soldered back together. This fixed the problem.

Then it was discovered that the switch for the right joystick controlling the left direction is broken. When it is press it stops the character moving left and the character will move left when not pressed. A replacement part is on order.

**Comment by wynnmade** [comment]
Needs a spring.
