### ISSUE TITLE
Museum: Fix Centiped P1 & P2 buttons

### ISSUE THREAD

**Issue by jesse-made** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#31]

**Comment by wynnmade** [comment]
If possible, break into smaller tasks.

**Comment by wynnmade** [comment]
@asajbel 

Opened up the cabinet and found that the start buttons had broken start buttons. Like from someone jamming on them. Replacements have been ordered.

**Comment by wynnmade** [comment]
Centipede appears to be working.
