### ISSUE TITLE
Museum: Virtual On Cabinet Repair

### ISSUE THREAD

**Issue by asajbel** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#43]
The Virtual On Slave Site is failing to initialize when the cabinet is turning on. The Slave Site will turn on and the marquee will light up.

When Virtual On cabinet turns on and initializes fine it ran the game's attract mode for about 4 mins before the slave site turned off the monitor causing the entire system to crash. I think the start button for the slave site turned off and the marquee stayed on. The same as if the slave site doesn't start.

**Comment by Tenfresh** [comment]
Issue has been diagnosed as the power supply -- a replacement is being sourced and will be installed.

**Comment by Tenfresh** [comment]
New power supply installed and everything is operational!

**Comment by asajbel** [comment]
Closing as the cabinet initialization problem is fixed. Currently there doesn't seem to be any major problems with the system. If there are, please make new issues to address them.
