### ISSUE TITLE
Museum: Wii U Digital Library

### ISSUE THREAD

**Issue by asajbel** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#49]
The Museum needs a solution to exhibit digital copies of our Wii U game collection to ensure the long term preservation of the material. The best solution would be 100% accurate to the system hardware and allow for the entire game library to be exhibited on a single system.

**Comment by wynnmade** [comment]
Duplicate of: https://github.com/Museum-of-Art-and-Digital-Entertainment/made_deploy/issues/577
