### ISSUE TITLE
Community: Tournaments: Smash 2024-06-04

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#66]
Tecson

**Comment by asajbel** [comment]
There was a low turnout this week of 12 people with 9 paid. Max put up the tournament page Monday morning. Turnout seems to be drifting downward.

**Comment by asajbel** [comment]
@wynnmade I'm not able to close MADE-Initiatives issues. Can @qst0?

**Comment by asajbel** [comment]
https://www.start.gg/tournament/smash-at-the-made-42-1/events.

Looking at the numbers this seems to an outliner. But we have had more people in the past and with the change in TO there might be something missing to generate interest and turnout. We have had numbers like this before for tournaments.
