### ISSUE TITLE
Community: Tournaments: Smash Ultimate 2024-06-18

### ISSUE THREAD

**Issue by asajbel** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#68]
Super Smash Bros. Ultimate Tournament, the 43rd in the series. 

Tournament Organizer: Max Meek

**Comment by wynnmade** [comment]
@asajbel I don't understand how this can be "In Progress" without a DRI. Can we get someone assigned to this?

**Comment by asajbel** [comment]
Still can't assign people to MADE_Initiative issues not even self assign. I would have self assigned for reporting.

**Comment by wynnmade** [comment]
Bummer! Okay, I'll assign you. I thought I'd fixed it. I may ping you again for more testing.
