### ISSUE TITLE
Operations: Website: Refactor for Strict Typing for Data Requests

### ISSUE THREAD

**Issue by wynnmade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#85]
In order to better support localization, we need to have strictly typed blobs for each of our widgets. This will allow us to automate localization for a first pass, then have a native speaker go in and fix it.

**Comment by PranavJayachand** [comment]
Add [Zod](https://github.com/colinhacks/zod) and move types to a Types.tsx file to ensure they're all the same and work properly

**Comment by wynnmade** [comment]
Moved to @MadHapps as DRI.

**Comment by wynnmade** [comment]
@MadHapps I'll help you break this down into subtasks.
