### ISSUE TITLE
Museum: Grant: Curriculum Development: Demographic data

### ISSUE THREAD

**Issue by Stacey-themade** [Museum-of-Art-and-Digital-Entertainment/MADE-Initiatives#98]

**Comment by Stacey-themade** [comment]
@wynnmade Can you provide me with this?

**Comment by wynnmade** [comment]
@Stacey-themade I'm not sure what sort of demographic data you're looking for, could you provide 3 to 5 types as well as what data fields they would contain?

**Comment by Stacey-themade** [comment]
@wynnmade I am looking for information on target population, numbers served, and cost per client.

**Comment by wynnmade** [comment]
Target population would currently be children aged 8 to 13, particularly in the Bay Area (more specifically Oakland), but not limited to these children. Numbers served would be 230 students in 2023, trending upwards. Cost per client is zero, as it is subsidized by donations, field trips, and admissions.

**Comment by wynnmade** [comment]
@Stacey-themade Can I close this issue, or do you need more?

**Comment by Stacey-themade** [comment]
No, you can close, thanks.

**Comment by wynnmade** [comment]
Awesome, thanks!
